version: "3"
services:
  # RabbitMQ for message passing between application services
  rabbitmq:
    image: rabbitmq:3.7.0-management-alpine
    volumes:
      - ./rabbit/config:/etc/rabbitmq/rabbitmq.config
    ports:
      - 2000:15672 # management panel; creds guest/guest
    networks:
      - backend

  # MongoDB for general-purpose, persistent data storage
  db:
    image: mongo:3.4.10-jessie
    volumes:
      - db-data:/data/db
    networks:
      - backend

  # nginx for glueing outside world with the application
  proxy:
    build: ./nginx
    ports:
      - 80:80
    networks:
      - frontend
    volumes:
      - ./nginx/conf:/etc/nginx
    depends_on:
      - "http-server"

  # Multiple instances of backend HTTP servers handling API requests
  http-server:
    build: ./http
    networks:
      - frontend
      - backend
    volumes:
      - files-data:/upload
    depends_on:
      - "rabbitmq"
      - "db"

  # Multiple instances of workers which convert the uploaded files.
  worker:
    build: ./worker
    networks:
      - backend
    volumes:
      - files-data:/upload
    depends_on:
      - "rabbitmq"
      - "db"

networks:
  backend:
  frontend:

volumes:
  db-data:
  media-data:
  files-data:
